# Generated by Django 4.2.23 on 2025-07-10 03:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tom_nonlocalizedevents', '0017_alter_eventsequence_external_coincidence_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NonLocalizedEventsProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treasuremap_username', models.CharField(blank=True, default='520520', max_length=255, null=True, verbose_name='TreasureMap Username')),
                ('_treasuremap_apikey_encrypted', models.BinaryField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
