# Generated by Django 5.2.16 on 2026-07-21 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tom_nonlocalizedevents', '0018_alter_eventlocalization_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nonlocalizedevent',
            name='event_type',
            field=models.CharField(choices=[('GW', 'Gravitational Wave'), ('GRB', 'Gamma-ray Burst'), ('NU', 'Neutrino'), ('XRT', 'X-ray Transient'), ('UNK', 'Unknown')], default='GW', help_text='The type of NonLocalizedEvent, used for determining how to ingest and display it', max_length=3),
        ),
    ]
