# Generated by Django 5.2.16 on 2026-07-21 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tom_nonlocalizedevents', '0019_alter_nonlocalizedevent_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventsequence',
            name='hermes_message_id',
            field=models.UUIDField(blank=True, help_text='The Hermes message UUID for the alert this sequence was ingested from (the hop kafka "_id" header). Null for sequences with no Hermes message, e.g. GraceDB back-fill.', null=True),
        ),
    ]
