name: Release to PyPi

on:
  release:
    types: [published]

jobs:
  publish_to_pypi:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install poetry
        poetry self add "poetry-dynamic-versioning[plugin]"
    - name: Build package and publish to PyPi
      run: |
        poetry build -f wheel
        poetry build -f sdist
        poetry publish -u "__token__" -p '${{ secrets.PYPI_TOM_NONLOCALIZEDEVENTS_API_TOKEN }}'
